### ISSUE TITLE
"-O get" stores uid as a list

### ISSUE THREAD

**Issue by mlawren** [renard/git-meta#1]
After running "git meta -O get" the .gitmeta file contains the following:

```
{
"etc/ssh/ssh_config": {
"uid": [
"root"
], 
"gid": "root", 
"mode": 33188, 
"mtime": 1293387162
}, 
```

"git meta set" does not expect the uid: field to be a list, and croaks with the following message:

```
Traceback (most recent call last):
  File "/usr/local/bin/git-meta", line 246, in <module>
    __init__()
  File "/usr/local/bin/git-meta", line 241, in __init__
    git_set_file_attributs(args)
  File "/usr/local/bin/git-meta", line 126, in git_set_file_attributs
    uid = pwd.getpwnam(data[file]['uid']).pw_uid
TypeError: must be string, not list
```

**Comment by mlawren** [comment]
In case it makes a difference, I'm running Python 2.7.3 on a Debian 7.7 (wheezy) system.
